const data = {
  n_tables: 10,
  table: [
    {
      active_status: 1,
      address:
        "19 EcoCentre Ambuja Neotia 4, EM Block, Sector V, Bidhannagar, Kolkata, West Bengal 700091",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "Salt Lake Sec V",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Altair Boutique Hotel",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Altair+boutique+hotel<s>",
      pincode: 700091,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol002",
      venufied: 0,
    },
    {
      active_status: 1,
      address: "Bara Dighi Tea Garden, West Bengal 735230\n",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "jalpaiguri",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Baradighi The Bungalow",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Baradighi+The+Bungalow<s>",
      pincode: 735230,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol003",
      venufied: 0,
    },
    {
      active_status: 1,
      address: "Village Beledanga Usthi Rd, Kalaria, Ushti, West Bengal 743375",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "Ushti",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Breathing Earth",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Breathing+earth<s>",
      pincode: 743375,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol004",
      venufied: 0,
    },
    {
      active_status: 1,
      address: "Chamong Tea Garden, Simana Basti, West Bengal 734216",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "Simana Basti",
      city: "Darjelling",
      extra_prov: "NAN",
      name: "Chamong Chiabari - Mountain Retreat & Spa",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Chamong+Chiabari+-+Mountain+Retreat+_+Spa<s>",
      pincode: 734216,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol007",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "Opposite Raghudevpur Gram Panchayat Office, Domjur - Bauria Rd, Raghudevpur, West Bengal 711322",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "Howrah",
      city: "Kolkata",
      extra_prov: "NAN",
      name: "Country Roads",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>country+roads<s>",
      pincode: 711322,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol008",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "17, Rafi Ahmed Kidwai Rd, near crown cinema, Janbazar, Taltala, Kolkata, West Bengal 700013",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "taltala",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Green Inn Banquets",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Green+Inn+banquets<s>",
      pincode: 700013,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol009",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "Biswa Bangla Sarani, near City Centre 2, Dash Drone, Rajarhat, Kolkata, West Bengal 700136",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "rajarhat",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Holiday Inn Kolkata Airport",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Holiday+Inn+Kolkata+airport<s>",
      pincode: 700136,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol00A",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "2, W Range, near Tata Motor lexus Showroom, Beck Bagan, Elgin, Kolkata, West Bengal 700017",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "park street",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Hotel Orion Westwillows",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>hotel+Orion+westwillows<s>",
      pincode: 700017,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol00B",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "641, VIP Rd, Ramkrishna Pally, Kaikhali, Kolkata, West Bengal 700052",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "Kaikhali",
      city: "Kolkata",
      extra_prov: "NAN",
      name: "Hotel Oxygen O2",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Hotel+Oxygen+O2<s>",
      pincode: 711322,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol00C",
      venufied: 0,
    },
    {
      active_status: 1,
      address:
        "Cf 12, BG Block(Newtown), Action Area 1C, Newtown, Kolkata, West Bengal 700156",
      amme: [
        "Veg Only",
        "Multiple Event Area",
        "Parking Available",
        "Valet Parking",
        "Air Conditioned",
        "Changing Room",
      ],
      area: "newtown",
      city: "kolkata",
      extra_prov: "NAN",
      name: "Ibis Kolkta Rajarhat Hotel",
      nphotos: 4,
      photos:
        "https:<s><s>s3.ap-south-1.amazonaws.com<s>venuefy.images<s>Venues<s>Ibis+kolkta+rajarhat+hotel<s>",
      pincode: 700156,
      review: "0(0)",
      starting_price: 0,
      state: "West Bengal",
      vcode: "VNFY0Kol00D",
      venufied: 0,
    },
  ],
};

export default data;
