const locations = ["Kolkata", "Chennai", "Delhi", "Allahabad"];

const selectMarks = [
  { value: 1, label: "50" },
  { value: 2, label: "100" },
  { value: 3, label: "200" },
  { value: 4, label: "300" },
  { value: 5, label: "500" },
  { value: 6, label: "1000" },
];

const capacity = {
  0: "0",
  1: "50",
  2: "100",
  3: "200",
  4: "300",
  5: "500",
  6: "1000",
  7: "1000+",
};

const listData = [
  {
    header: "Venue Type",
    checkboxes: [
      { label: "Banquet Halls", name: "bnqt_hl" },
      { label: "Resorts", name: "rsrt" },
      { label: "Hotel Banquets", name: "hotl_bnqt" },
    ],
    // reset: {
    //   bnqt_hl: false,
    //   rsrt: false,
    //   hotl_bnqt: false,
    // },
  },
  {
    header: "Venue Features",
    checkboxes: [
      { label: "Only Veg", name: "veg_only" },
      { label: "Multiple Event Areas", name: "mea" },
      { label: "Venuefied", name: "venuefied" },
      { label: "Air Conditioning", name: "air_cond" },
      { label: "Changing Rooms", name: "chng_rms" },
      {
        label: "Space Type",
        name: "spc_typ",
        collapsable: true,
        checkboxes: [
          { label: "Pool Side", name: "st_1" },
          { label: "Rooftop", name: "st_2" },
          { label: "Open Space", name: "st_3" },
          { label: "Indoor", name: "st_4" },
          { label: "Lawn", name: "st_5" },
        ],
      },
      {
        label: "Parking",
        name: "prk_typ",
        collapsable: true,
        checkboxes: [
          { label: "Valet Parking", name: "pt_valet" },
          { label: "upto 20 vehicles", name: "pt_1" },
          { label: "20-50 vehicles", name: "pt_2" },
          { label: "50-100 vehicles", name: "pt_3" },
          { label: "100-500 vehicles", name: "pt_4" },
          { label: "500+ vehicles", name: "pt_5" },
        ],
      },
      {
        label: "Catering",
        name: "cat_typ",
        collapsable: true,
        checkboxes: [
          { label: "Inhouse Catering", name: "cat_1" },
          { label: "Outside Catering", name: "cat_2" },
        ],
      },
      {
        label: "Decoration",
        name: "dec_typ",
        collapsable: true,
        checkboxes: [
          { label: "Inhouse Decoration", name: "dec_1" },
          { label: "Outside Decoration", name: "dec_2" },
        ],
      },
      {
        label: "Permissions",
        name: "perm_typ",
        collapsable: true,
        checkboxes: [
          { label: "Late Night Music", name: "perm_1" },
          { label: "Late Night Wedding", name: "perm_2" },
          { label: "Barat Allowed", name: "perm_3" },
          { label: "Hawan Allowed", name: "perm_4" },
          { label: "Fire-Crackers Allowed", name: "perm_5" },
          { label: "Multiple Wedding", name: "perm_6" },
        ],
      },
    ],
    // reset: {
    //   veg_only: false,
    //   mea: false,
    //   venuefied: false,
    //   air_cond: false,
    //   chng_rms: false,
    //   st_1: false,
    //   st_2: false,
    //   st_3: false,
    //   st_4: false,
    //   st_5: false,
    //   pt_valet: false,
    //   pt_1: false,
    //   pt_2: false,
    //   pt_3: false,
    //   pt_4: false,
    //   pt_5: false,
    //   cat_1: false,
    //   cat_2: false,
    //   dec_1: false,
    //   dec_2: false,
    //   perm_1: false,
    //   perm_2: false,
    //   perm_3: false,
    //   perm_4: false,
    //   perm_5: false,
    //   perm_6: false,
    // },
  },
];

const resetParams = {
  air_cond: false,
  bnqt_hl: false,
  cat_1: false,
  cat_2: false,
  chng_rms: false,
  dec_1: false,
  dec_2: false,
  hotl_bnqt: false,
  location: "Unspecified",
  mea: false,
  perm_1: false,
  perm_2: false,
  perm_3: false,
  perm_4: false,
  perm_5: false,
  perm_6: false,
  pt_1: false,
  pt_2: false,
  pt_3: false,
  pt_4: false,
  pt_5: false,
  pt_valet: false,
  rsrt: false,
  st_1: false,
  st_2: false,
  st_3: false,
  st_4: false,
  st_5: false,
  veg_only: false,
  venuefied: false,
};

export { locations, selectMarks, capacity, listData, resetParams };
